
POST   http://localhost:5000/api/v1/users
Content-Type: application/json

{
  "email": "salan@gmail.com",
  "name": "string",
  "password": "string",
  "role": "admin"
  
}
###

POST   http://localhost:5000/api/v1/categories
Content-Type: application/json

{
  "name": "Capatos"
 
  
  
}

###

PUT   http://localhost:5000/api/v1/categories/1
Content-Type: application/json

{
  "name": "Gas"
 
  
  
}