###Categorias
GET  http://localhost:5000/api/v1/categories/3
###
GET  http://localhost:5000/api/v1/categories/?page=1&pageSize=1
###
POST  http://localhost:5000/api/v1/categories
Content-Type: application/json

{
  "name":"Madera"
 
}

###
PUT   http://localhost:5000/api/v1/categories/string
Content-Type: application/json

{
  "name": "Gas"
}

###
DELETE http://localhost:5000/api/v1/categories/2

###Productos
GET http://localhost:5000/api/v1/products/1
###
POST  http://localhost:5000/api/v1/products
Content-Type: application/json

{
  "title": "Producto de prueba2",
  "price": 1,
  "description": "Este es un producto de prueba",
  "categoryId":1,
  "images": ["https://placeimg.com/640/480/any"]
}
###
PUT http://localhost:5000/api/v1/products/3
Content-Type: application/json

{
  "title": "Producto editado2",
  "price":10,
  "description": "Este es un producto de prueba",
  "categoryId":1,
  "images": ["https://placeimg.com/640/480/any"]
}
###
DELETE http://localhost:5000/api/v1/products/2

###Usuarios
GET http://localhost:5000/api/v1/users/4
###
POST http://localhost:5000/api/v1/users
Content-Type: application/json

{
  "email": "example@gmail.com",
  "name":"alan56",
  "password":"1234567",
  "role":"admin"

}

###
PUT http://localhost:5000/api/v1/users/5
Content-Type: application/json

{
  
  "name":"alanedit",
  "password":"12345678"

}

###
DELETE http://localhost:5000/api/v1/users/5

###Auth
POST http://localhost:5000/api/v1/auth/login
Content-Type: application/json

{
  "email":"salan@gmail.com",
  "password":"string"
}



